#!/bin/bash

# 🚀 EcoGuard AI - Simple Deployment Script
# This script helps you deploy to Render.com

echo "======================================"
echo "🚀 EcoGuard AI Deployment Helper"
echo "======================================"
echo ""

# Check if we're in the right directory
if [ ! -f "backend/main.py" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "✅ Project structure verified"
echo ""

# Step 1: Create deployment package
echo "📦 Creating deployment package..."
zip -r ecoguard-deploy.zip . \
    -x "*.git*" \
    -x "*__pycache__*" \
    -x "*.pyc" \
    -x "backend/data/predictions.db" \
    -x "project.zip" \
    -x ".DS_Store"

echo "✅ Deployment package created: ecoguard-deploy.zip"
echo ""

# Step 2: Show deployment instructions
echo "======================================"
echo "📋 DEPLOYMENT INSTRUCTIONS"
echo "======================================"
echo ""
echo "Choose one of these options:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 OPTION 1: Render.com (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository:"
echo "   https://github.com/jeevanelias1-source/EcoGuard-AI"
echo "5. Render will auto-detect your settings from render.yaml"
echo "6. Add environment variables (see below)"
echo "7. Click 'Create Web Service'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 OPTION 2: Fix GitHub & Push"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "  # Install GitHub CLI"
echo "  brew install gh"
echo ""
echo "  # Authenticate"
echo "  gh auth login"
echo "  # Select: GitHub.com → HTTPS → Yes → Login with browser"
echo "  # Make sure to login as 'jeevanelias1-source'"
echo ""
echo "  # Push your code"
echo "  git push origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 OPTION 3: Manual GitHub Upload"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/jeevanelias1-source/EcoGuard-AI"
echo "2. Make sure you're logged in as 'jeevanelias1-source'"
echo "3. Click 'Add file' → 'Upload files'"
echo "4. Drag and drop all your updated files"
echo "5. Commit changes"
echo "6. Then deploy to Render (see Option 1)"
echo ""
echo "======================================"
echo "🔑 ENVIRONMENT VARIABLES"
echo "======================================"
echo ""
echo "Add these in your hosting platform:"
echo ""
echo "  OPENWEATHER_API_KEY=your_openweather_key"
echo "  OPENAQ_API_KEY=your_openaq_key"
echo "  SMTP_USER=your_email@gmail.com"
echo "  SMTP_PASS=your_gmail_app_password"
echo "  SMTP_HOST=smtp.gmail.com"
echo "  SMTP_PORT=587"
echo "  RECIPIENT_EMAIL=jeevanelias1@gmail.com"
echo "  TWILIO_ACCOUNT_SID=your_twilio_sid"
echo "  TWILIO_AUTH_TOKEN=your_twilio_token"
echo "  TWILIO_PHONE_NUMBER=your_twilio_number"
echo "  EMERGENCY_SMS_NUMBER=+916238275699"
echo ""
echo "======================================"
echo "📝 IMPORTANT NOTES"
echo "======================================"
echo ""
echo "1. Gmail App Password:"
echo "   - Go to: https://myaccount.google.com/security"
echo "   - Enable 2-Factor Authentication"
echo "   - Create App Password for 'Mail'"
echo "   - Use this password for SMTP_PASS"
echo ""
echo "2. API Keys:"
echo "   - OpenWeather: https://openweathermap.org/api"
echo "   - OpenAQ: https://openaq.org/"
echo "   - Twilio: https://www.twilio.com/"
echo ""
echo "3. After deployment, your app will be at:"
echo "   https://ews-kerala-safeai.onrender.com"
echo ""
echo "======================================"
echo "✅ Ready to deploy!"
echo "======================================"
echo ""
echo "Deployment package saved as: ecoguard-deploy.zip"
echo ""
